apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-app
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: backstage/backstage-app
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
